### ISSUE TITLE
ftp timeout on pipeline_download

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#741]
Hi @mrow84 @rtblackwell 
If you have a sec, @claireh93 and I are having a problem with the ftp downloading timing out when we try to download some (not enormous) files. The `config.yaml` is just:
```
data_directory: data
access_log: access-{run_id}.yaml

run_metadata:
  default_input_namespace: SCRC
  default_output_namespace: Simulation.jl

read:
  - where:
      data_product: human/infection/SARS-CoV-2/asymptomatic-period
  - where:
      data_product: human/demographics/population/scotland
      component: grid1km/age/persons
  - where:
      data_product: records/pollution
```

But when I run it, I just get a timeout halfway through downloading:
```
(data_pipeline_api) bleaberry[~/tmp] pipeline_download --config config.yaml
[2020-08-25 13:48:35,776] [data_pipeline_api.registry.download] [INFO] Read config for data_product: human/infection/SARS-CoV-2/asymptomatic-period, namespace: SCRC, component: None, version: None
[2020-08-25 13:48:35,776] [data_pipeline_api.registry.download] [INFO] Read config for data_product: human/demographics/population/scotland, namespace: SCRC, component: grid1km/age/persons, version: None
[2020-08-25 13:48:35,776] [data_pipeline_api.registry.download] [INFO] Read config for data_product: records/pollution, namespace: SCRC, component: None, version: None
[2020-08-25 13:48:35,776] [data_pipeline_api.registry.downloader] [INFO] Starting download
...
[2020-08-25 13:48:42,783] [data_pipeline_api.registry.downloader] [INFO] Downloading public data from uri: ftp://boydorr.gla.ac.uk/scrc/, path: records/pollution/0.1.0.h5 to data/records/pollution/0.1.0/0.1.0.h5
drwxrwsr-x   15 113      121          4096 Aug 11 12:13 scrc
drwxrwsr-x    2 113      121          4096 Jul 22 16:30 simple_network_sim
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/bin/pipeline_download", line 8, in <module>
    sys.exit(download_cli())
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/data_pipeline_api/registry/download.py", line 148, in download_cli
    download_from_config_file(config_filename=config, token=token)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/data_pipeline_api/registry/download.py", line 129, in download_from_config_file
    download_from_configs(run_metadata, read_configs, token, root)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/data_pipeline_api/registry/download.py", line 108, in download_from_configs
    downloader.download()
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/data_pipeline_api/registry/downloader.py", line 426, in download
    self._download()
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/data_pipeline_api/registry/downloader.py", line 336, in _download
    fs.get(source_path, output_path.as_posix(), **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/fsspec/spec.py", line 614, in get
    data = f1.read(self.blocksize)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/fsspec/spec.py", line 1239, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/fsspec/caching.py", line 156, in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/site-packages/fsspec/implementations/ftp.py", line 239, in _fetch_range
    callback=callback,
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/ftplib.py", line 442, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/ftplib.py", line 361, in ntransfercmd
    source_address=self.source_address)
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/Caskroom/miniconda/base/envs/data_pipeline_api/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```
Using wget I can download the file in a few seconds without any problems, but using `pipeline_download` it times out before it completes (for me and Claire). It also doesn't check whether the file is already downloaded (which I kind of expected it to do), so even if I download it using wget it just starts downloading it again and times out...

Any possible help gratefully received?

**Comment by richardreeve** [comment]
@kzscisoft - I was wondering if you had time to have a look at this since you've been looking at the pipeline recently. It seems reproducible for me and Claire, but I'm not sure whether it's macs or a general thing? No problem if you're busy...

**Comment by claireh93** [comment]
@richardreeve I haven't had this problem today - seems to be downloading the demographic data and params fine now - strange! Does it work for you now?

**Comment by richardreeve** [comment]
No, I still get a timeout when it tries to download `records/pollution/0.1.0.h5` with the config file above. Good if it's working for you though.

**Comment by claireh93** [comment]
Seems to work for me fine including the pollution data - only difference with my config file is I just have `namespace` instead of:
```
run_metadata:
  default_input_namespace: SCRC
  default_output_namespace: Simulation.jl
```
I don't know if/why this should make a difference!

**Comment by richardreeve** [comment]
I think that's because SimulationData has pinned data_pipeline_api to 0.7.0, whereas I'm using the latest version (0.7.3) which allows both to be selected separately.

**Comment by richardreeve** [comment]
If I do it through Julia so I'm using 0.7.0 I get exactly the same result though (a timeout error).

**Comment by claireh93** [comment]
Ah now I have tried to download the lookup table it has timed out, the other stuff appeared to work fine for a while there though
